name: auto update cv from overleaf
on:
  push:
    branches:
      - 'master'
jobs:
  update_cv:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@master
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository have been cloned to the runner."
      - run: echo "ğŸŒ The repo is now cloned on the runner"
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository (Useful for debugging)
        run: |
          ls -la ${{ github.workspace }}
      - name: Download cv
        run: |
          wget -O ${{ github.workspace }}/media/wang_cv.pdf "https://www.overleaf.com/download/project/611aa382c9405d7f3ad1041e/build/183d7600784-59012a4669cd3e34/output/output.pdf?compileGroup=priority&clsiserverid=clsi-pre-emp-c2d-c-f-rmz7&popupDownload=true"
      - name: Commit the results
        run: |
          git config --local user.name "robot"
          git add .
          git commit -m "automated cv update"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
      - name: List current working directory
        run: |
          ls -la          
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      

